version: 2.1

orbs:
  redmine-plugin: agileware-jp/redmine-plugin@3.6.1

jobs:
  rspec:
    parameters:
      redmine_version:
        type: string
      ruby_version:
        type: string
      db:
        type: enum
        enum: ['mysql', 'pg']
      db_version:
        type: string
    executor:
      name: redmine-plugin/ruby-<< parameters.db >>
      ruby_version: << parameters.ruby_version >>
      db_version: << parameters.db_version >>
    steps:
      - checkout
      - redmine-plugin/download-redmine:
          version: << parameters.redmine_version >>
      - redmine-plugin/install-self
      - redmine-plugin/generate-database_yml
      - redmine-plugin/bundle-install
      - run: sudo apt-get install fonts-migmix
      - redmine-plugin/rspec:
          test_migration_rollback: false
      - store_artifacts:
          path: redmine/tmp/capybara
          destination: screenshots

ignore_trial: &ignore_trial
  filters:
    branches:
      ignore:
        - trial

default_context: &default_context
  context:
    - lychee-ci-environment

workflows:
  version: 2
  test:
    jobs:
      - rspec:
          <<: *default_context
          <<: *ignore_trial
          name: RSpec on supported maximum versions with PostgreSQL
          redmine_version: $REDMINE_MAX_VERSION
          ruby_version: $RUBY_MAX_VERSION
          db: pg
          db_version: $POSTGRES_VERSION
      - rspec:
          <<: *default_context
          <<: *ignore_trial
          name: RSpec on supported minimum versions with MySQL
          redmine_version: $REDMINE_MIN_VERSION
          ruby_version: $RUBY_MIN_VERSION
          db: mysql
          db_version: $MYSQL_VERSION
